-- Dynamic Table: Silver Layer - Facilities
-- Source: BRONZE.BASE_FACILITIES
-- Refresh: 30 minutes lag, AUTO mode

CREATE OR REPLACE DYNAMIC TABLE TRACKMAN_DW.SILVER.SLV_FACILITIES(
    FACILITY_ID,
    FACILITY_NAME,
    FACILITY_TYPE,
    COUNTRY,
    REGION,
    CITY,
    NUM_BAYS,
    OPERATING_HOURS_START,
    OPERATING_HOURS_END,
    DAILY_OPERATING_HOURS,
    IS_COMMERCIAL,
    OPENING_DATE,
    IS_ACTIVE,
    PROCESSED_AT
)
TARGET_LAG = '30 minutes'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = COMPUTE_WH
AS
SELECT
    FACILITY_ID,
    TRIM(FACILITY_NAME) AS FACILITY_NAME,
    UPPER(FACILITY_TYPE) AS FACILITY_TYPE,
    UPPER(COUNTRY) AS COUNTRY,
    UPPER(REGION) AS REGION,
    TRIM(INITCAP(CITY)) AS CITY,
    NUM_BAYS,
    OPERATING_HOURS_START,
    OPERATING_HOURS_END,
    (OPERATING_HOURS_END - OPERATING_HOURS_START) AS DAILY_OPERATING_HOURS,
    IS_COMMERCIAL,
    OPENING_DATE,
    IS_ACTIVE,
    CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM TRACKMAN_DW.BRONZE.BASE_FACILITIES
WHERE FACILITY_ID IS NOT NULL;
