-- Dynamic Table: Silver Layer - Players
-- Source: BRONZE.BASE_PLAYERS
-- Refresh: 30 minutes lag, AUTO mode

CREATE OR REPLACE DYNAMIC TABLE TRACKMAN_DW.SILVER.SLV_PLAYERS(
    PLAYER_ID,
    PLAYER_NAME,
    FIRST_NAME,
    LAST_NAME,
    COUNTRY,
    REGION,
    HANDICAP_INDEX,
    MEMBERSHIP_TIER,
    IS_ACTIVE,
    PROCESSED_AT
)
TARGET_LAG = '30 minutes'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = COMPUTE_WH
AS
SELECT
    PLAYER_ID,
    TRIM(PLAYER_NAME) AS PLAYER_NAME,
    TRIM(INITCAP(FIRST_NAME)) AS FIRST_NAME,
    TRIM(INITCAP(LAST_NAME)) AS LAST_NAME,
    UPPER(COUNTRY) AS COUNTRY,
    UPPER(REGION) AS REGION,
    ROUND(HANDICAP_INDEX, 1) AS HANDICAP_INDEX,
    UPPER(MEMBERSHIP_TIER) AS MEMBERSHIP_TIER,
    IS_ACTIVE,
    CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM TRACKMAN_DW.BRONZE.BASE_PLAYERS
WHERE PLAYER_ID IS NOT NULL;
