-- Dynamic Table: Silver Layer - Courses
-- Source: BRONZE.BASE_COURSES
-- Refresh: 30 minutes lag, AUTO mode

CREATE OR REPLACE DYNAMIC TABLE TRACKMAN_DW.SILVER.SLV_COURSES(
    COURSE_ID,
    COURSE_NAME,
    COUNTRY,
    PAR,
    YARDAGE,
    COURSE_RATING,
    SLOPE_RATING,
    IS_PREMIUM,
    PROCESSED_AT
)
TARGET_LAG = '30 minutes'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = COMPUTE_WH
AS
SELECT
    COURSE_ID,
    TRIM(COURSE_NAME) AS COURSE_NAME,
    UPPER(COUNTRY) AS COUNTRY,
    PAR,
    YARDAGE,
    ROUND(COURSE_RATING, 1) AS COURSE_RATING,
    SLOPE_RATING,
    IS_PREMIUM,
    CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM TRACKMAN_DW.BRONZE.BASE_COURSES
WHERE COURSE_ID IS NOT NULL;
