-- Dynamic Table: Gold Layer - Bay Insights
-- Sources: SILVER.SLV_BAY_BOOKINGS, SILVER.SLV_FACILITIES
-- Refresh: 30 minutes lag, AUTO mode

CREATE OR REPLACE DYNAMIC TABLE TRACKMAN_DW.GOLD.DT_BAY_INSIGHTS(
    BAY_ID,
    FACILITY_NAME,
    TOTAL_BOOKED_HOURS,
    AVG_PLAYERS_PER_BOOKING,
    DAYS_WITH_ACTIVITY
)
TARGET_LAG = '30 minutes'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = COMPUTE_WH
AS
SELECT
    b.BAY_ID,
    f.FACILITY_NAME,
    SUM(b.DURATION_HOURS) AS TOTAL_BOOKED_HOURS,
    ROUND(AVG(b.NUM_PLAYERS), 1) AS AVG_PLAYERS_PER_BOOKING,
    COUNT(DISTINCT b.BOOKING_DATE) AS DAYS_WITH_ACTIVITY
FROM TRACKMAN_DW.SILVER.SLV_BAY_BOOKINGS b
JOIN TRACKMAN_DW.SILVER.SLV_FACILITIES f 
    ON b.FACILITY_ID = f.FACILITY_ID
WHERE b.IS_OCCUPIED = TRUE
GROUP BY b.BAY_ID, f.FACILITY_NAME;
