-- Dynamic Table: Gold Layer - Bay Occupation Heatmap
-- Source: SILVER.SLV_BAY_BOOKINGS
-- Refresh: 30 minutes lag, AUTO mode

CREATE OR REPLACE DYNAMIC TABLE TRACKMAN_DW.GOLD.DT_BAY_OCCUPATION_HEATMAP(
    DAY_OF_WEEK,
    HOUR_OF_DAY,
    TOTAL_BOOKINGS,
    OCCUPIED_SLOTS,
    OCCUPANCY_PCT,
    AVG_PLAYERS
)
TARGET_LAG = '30 minutes'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = COMPUTE_WH
AS
SELECT
    DAY_OF_WEEK,
    HOUR_OF_DAY,
    COUNT(*) AS TOTAL_BOOKINGS,
    SUM(CASE WHEN IS_OCCUPIED THEN 1 ELSE 0 END) AS OCCUPIED_SLOTS,
    ROUND(SUM(CASE WHEN IS_OCCUPIED THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) AS OCCUPANCY_PCT,
    ROUND(AVG(NUM_PLAYERS), 1) AS AVG_PLAYERS
FROM TRACKMAN_DW.SILVER.SLV_BAY_BOOKINGS
GROUP BY DAY_OF_WEEK, HOUR_OF_DAY;
