-- Dynamic Table: Gold Layer - Club Performance
-- Source: SILVER.SLV_SHOTS
-- Refresh: 30 minutes lag, AUTO mode

CREATE OR REPLACE DYNAMIC TABLE TRACKMAN_DW.GOLD.DT_CLUB_PERFORMANCE(
    CLUB_ID,
    TOTAL_SHOTS,
    AVG_BALL_SPEED,
    AVG_CLUB_SPEED,
    AVG_SMASH_FACTOR,
    AVG_LAUNCH_ANGLE,
    AVG_SPIN_RATE,
    AVG_CARRY,
    AVG_TOTAL_DISTANCE
)
TARGET_LAG = '30 minutes'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = COMPUTE_WH
AS
SELECT
    CLUB_ID,
    COUNT(*) AS TOTAL_SHOTS,
    ROUND(AVG(BALL_SPEED), 1) AS AVG_BALL_SPEED,
    ROUND(AVG(CLUB_SPEED), 1) AS AVG_CLUB_SPEED,
    ROUND(AVG(SMASH_FACTOR), 3) AS AVG_SMASH_FACTOR,
    ROUND(AVG(LAUNCH_ANGLE), 1) AS AVG_LAUNCH_ANGLE,
    ROUND(AVG(SPIN_RATE), 0) AS AVG_SPIN_RATE,
    ROUND(AVG(CARRY_DISTANCE), 1) AS AVG_CARRY,
    ROUND(AVG(TOTAL_DISTANCE), 1) AS AVG_TOTAL_DISTANCE
FROM TRACKMAN_DW.SILVER.SLV_SHOTS
GROUP BY CLUB_ID;
