-- Dynamic Table: Gold Layer - Course Analytics
-- Source: SILVER.SLV_SCORECARDS
-- Refresh: 30 minutes lag, AUTO mode

CREATE OR REPLACE DYNAMIC TABLE TRACKMAN_DW.GOLD.DT_COURSE_ANALYTICS(
    COURSE_ID,
    COURSE_NAME,
    ROUNDS_PLAYED,
    UNIQUE_PLAYERS,
    AVG_SCORE,
    AVG_VS_PAR,
    AVG_GIR_PCT,
    AVG_FIR_PCT,
    AVG_PUTTS_PER_HOLE,
    COMPLETED_ROUNDS,
    COMPLETION_PCT
)
TARGET_LAG = '30 minutes'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = COMPUTE_WH
AS
SELECT
    COURSE_ID,
    COURSE_NAME,
    COUNT(*) AS ROUNDS_PLAYED,
    COUNT(DISTINCT PLAYER_ID) AS UNIQUE_PLAYERS,
    ROUND(AVG(TOTAL_STROKES), 1) AS AVG_SCORE,
    ROUND(AVG(SCORE_VS_PAR), 1) AS AVG_VS_PAR,
    ROUND(AVG(GIR_PERCENTAGE), 1) AS AVG_GIR_PCT,
    ROUND(AVG(FIR_PERCENTAGE), 1) AS AVG_FIR_PCT,
    ROUND(AVG(PUTTS_PER_HOLE), 2) AS AVG_PUTTS_PER_HOLE,
    SUM(CASE WHEN IS_COMPLETE THEN 1 ELSE 0 END) AS COMPLETED_ROUNDS,
    ROUND(SUM(CASE WHEN IS_COMPLETE THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) AS COMPLETION_PCT
FROM TRACKMAN_DW.SILVER.SLV_SCORECARDS
GROUP BY COURSE_ID, COURSE_NAME;
