-- Dynamic Table: Gold Layer - Game Analytics
-- Source: SILVER.SLV_SESSIONS
-- Refresh: 30 minutes lag, AUTO mode

CREATE OR REPLACE DYNAMIC TABLE TRACKMAN_DW.GOLD.DT_GAME_ANALYTICS(
    SESSION_CATEGORY,
    TIME_OF_DAY,
    TOTAL_SESSIONS,
    AVG_DURATION,
    UNIQUE_PLAYERS,
    AVG_GROUP_SIZE
)
TARGET_LAG = '30 minutes'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = COMPUTE_WH
AS
SELECT
    SESSION_CATEGORY,
    TIME_OF_DAY,
    COUNT(*) AS TOTAL_SESSIONS,
    ROUND(AVG(DURATION_MINUTES), 1) AS AVG_DURATION,
    COUNT(DISTINCT PLAYER_ID) AS UNIQUE_PLAYERS,
    ROUND(AVG(NUM_PLAYERS), 1) AS AVG_GROUP_SIZE
FROM TRACKMAN_DW.SILVER.SLV_SESSIONS
GROUP BY SESSION_CATEGORY, TIME_OF_DAY;
