-- Dynamic Table: Gold Layer - Session Overview
-- Source: SILVER.SLV_SESSIONS
-- Refresh: 30 minutes lag, AUTO mode

CREATE OR REPLACE DYNAMIC TABLE TRACKMAN_DW.GOLD.DT_SESSION_OVERVIEW(
    SESSION_CATEGORY,
    SESSION_TYPE,
    TOTAL_SESSIONS,
    TOTAL_PLAYERS,
    AVG_DURATION_MINS,
    UNIQUE_PLAYERS
)
TARGET_LAG = '30 minutes'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = COMPUTE_WH
AS
SELECT
    SESSION_CATEGORY,
    SESSION_TYPE,
    COUNT(*) AS TOTAL_SESSIONS,
    SUM(NUM_PLAYERS) AS TOTAL_PLAYERS,
    ROUND(AVG(DURATION_MINUTES), 1) AS AVG_DURATION_MINS,
    COUNT(DISTINCT PLAYER_ID) AS UNIQUE_PLAYERS
FROM TRACKMAN_DW.SILVER.SLV_SESSIONS
GROUP BY SESSION_CATEGORY, SESSION_TYPE;
