-- Dynamic Table: Gold Layer - Weekly Trends
-- Source: SILVER.SLV_SESSIONS
-- Refresh: 30 minutes lag, AUTO mode

CREATE OR REPLACE DYNAMIC TABLE TRACKMAN_DW.GOLD.DT_WEEKLY_TRENDS(
    WEEK_START,
    SESSION_CATEGORY,
    SESSIONS,
    UNIQUE_PLAYERS,
    TOTAL_HOURS
)
TARGET_LAG = '30 minutes'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = COMPUTE_WH
AS
SELECT
    DATE_TRUNC('WEEK', SESSION_DATE) AS WEEK_START,
    SESSION_CATEGORY,
    COUNT(*) AS SESSIONS,
    COUNT(DISTINCT PLAYER_ID) AS UNIQUE_PLAYERS,
    SUM(DURATION_MINUTES) / 60 AS TOTAL_HOURS
FROM TRACKMAN_DW.SILVER.SLV_SESSIONS
GROUP BY DATE_TRUNC('WEEK', SESSION_DATE), SESSION_CATEGORY;
