name: 'trackman_dbt'
version: '1.0.0'
config-version: 2

profile: 'trackman_dbt'

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  trackman_dbt:
    bronze:
      +schema: bronze
      +materialized: view
    silver:
      +schema: silver
      +materialized: incremental
      +incremental_strategy: merge
    gold:
      +schema: gold
      +materialized: table
